### ISSUE TITLE
Coq segfaults during build

### ISSUE THREAD

**Issue by Sudha247** [ocamllabs/ocaml-multicore#646]
Tracking error reported by @ejgallego in https://github.com/ocaml-bench/sandmark/issues/248#issuecomment-914369736.
Steps for reproduction:

1. Clone the multicore support branch from https://github.com/ejgallego/coq/tree/ocaml+multicore
2. Build commands:
```
$ ./configure -bytecode-compiler no
$ make
```
results in a segfault.

3. Failing step:
```
$ dune build theories/
$ cd _build/default
$ rr record  ../install/default/bin/coqc -q -w -deprecated-native-compiler-option -w -native-compiler-disabled -native-compiler ondemand -boot -noinit -I /home/sudha/.opam/4.12+domains/lib/ocaml -I /home/sudha/.opam/4.12+domains/lib/ocaml/threads -I /home/sudha/.opam/4.12+domains/lib/zarith -I clib -I config -I engine -I gramlib -I interp -I kernel -I kernel/byterun -I lib -I library -I parsing -I plugins/btauto -I plugins/cc -I plugins/derive -I plugins/extraction -I plugins/firstorder -I plugins/funind -I plugins/ltac -I plugins/micromega -I plugins/nsatz -I plugins/ring -I plugins/rtauto -I plugins/ssr -I plugins/ssrmatching -I plugins/ssrsearch -I plugins/syntax -I pretyping -I printing -I proofs -I stm -I sysinit -I tactics -I vernac -R theories Coq -R theories Coq theories/Init/Byte.v
```

Backtrace:

```
#0  caml_darken (v=94262115352192, ignored=<optimized out>, state=<optimized out>) at major_gc.c:773
#1  0x000055bb1be9fc13 in scan_native_globals (fdata=0x0, f=0x55bb1be884e0 <caml_darken>) at globroots.c:214
#2  caml_scan_global_roots (f=f@entry=0x55bb1be884e0 <caml_darken>, fdata=fdata@entry=0x0) at globroots.c:238
#3  0x000055bb1be88f58 in cycle_all_domains_callback (domain=0x7f3742280000, unused=unused@entry=0x0, participating_count=<optimized out>, 
    participating=participating@entry=0x55bb1c864780 <stw_request+64>) at major_gc.c:1092
#4  0x000055bb1bea8438 in caml_try_run_on_all_domains_with_spin_work (handler=<optimized out>, data=<optimized out>, leader_setup=<optimized out>, 
    enter_spin_callback=<optimized out>, enter_spin_data=<optimized out>) at domain.c:932
#5  0x000055bb1be89c46 in major_collection_slice (howmuch=<optimized out>, participant_count=participant_count@entry=0, barrier_participants=barrier_participants@entry=0x0, 
    mode=mode@entry=Slice_interruptible) at major_gc.c:1376
#6  0x000055bb1be89dc7 in caml_major_collection_slice (howmuch=howmuch@entry=-1) at major_gc.c:1395
#7  0x000055bb1bea6f65 in caml_poll_gc_work () at domain.c:996
#8  0x000055bb1be873f5 in caml_garbage_collection () at signals_nat.c:110
#9  0x000055bb1bea9b97 in caml_call_gc ()

```

**Comment by ejgallego** [comment]
Thanks a lot @Sudha247 , even if the bytecode machine is disabled, there are still a few places where C code is called for initialization, I should fix those to provide real OCaml wrappers before we lose more time on this.

But I am not

By the way, a quicker building path these days is:
```
make -f Makefile.dune
```
This will call configure automatically, and use dune for the full build.

**Comment by ejgallego** [comment]
I have removed both the VM and the native backend from Coq in this branch https://github.com/ejgallego/coq/tree/ocaml%2Bmulticore_remove_vm and now Coq compiles now.

It is thus a problem on Coq side; I guess at some point we have to start thinking of porting the VM / native.

Meanwhile I suggest you folks use that branch.

**Comment by kayceesrk** [comment]
Thanks @ejgallego! We shall use this for our experiments.

**Comment by shakthimaan** [comment]
Thank you @ejgallego. 

Would it be possible to provide a tagged release such as https://github.com/ejgallego/coq/archive/multicore-t01.zip for our testing, or do you recommend that we pin and use the branch?

**Comment by ejgallego** [comment]
Sure, I will do a tag.

**Comment by ejgallego** [comment]
Here it is https://github.com/ejgallego/coq/releases/tag/multicore-2021-09-24 

Verified "working for me" (famous last words)
